# This configuration file enables global mapping by removing decay and radius clearing.
#
/**:
  ros__parameters:
    # printing statistics on console
    print_timings_to_console: false
    # Lidar settings
    use_lidar: false
    # QoS settings
    input_qos: "SENSOR_DATA"

    mapping_type: "static_tsdf"  # ["static_tsdf", "static_occupancy"]

     # color settings
    use_color: false
   
   # Frames
    map_clearing_frame_id: "base_link"  # Map clearing settings
    global_frame: "map" #The name of the TF frame in which the map is built.
    

    # Debug Parameters
    # printing statistics on console
    # print_rates_to_console: true
    # print_timings_to_console: true
    # print_delays_to_console: true
    # print_queue_drops_to_console: true
    # print_statistics_on_console_period_ms: 3000


    # Depth integration rate limit
    integrate_depth_rate_hz: 35.0

    # Limit visualization overhead
    integrate_color_rate_hz: -1.0  # no color while mapping
    update_mesh_rate_hz: -1.0 # no mesh while mapping
    layer_visualization_exclusion_height_m: 1.4      #Voxels with a z coordinate above this value are not visualized.
    layer_visualization_exclusion_radius_m: 7.0
    
    # Visualization
    slice_visualization_attachment_frame_id: "base_link"
    layer_streamer_bandwidth_limit_mbps: -1.0
    esdf_mode: "2d" # ["2d", "3d"]

    static_mapper:
      # projective integrators
      # projective_integrator_weighting_mode: "kInverseSquareWeight"
      projective_integrator_max_integration_distance_m: 5.0  # Distance to map

      # view calculator
      raycast_subsampling_factor: 4
      workspace_bounds_type: "height_bounds" # ["unbounded", "height_bounds", "bounding_box"]
      workspace_bounds_min_height_m: 0.0 # Remove cars bottom gap #minimal height of the workspace bounds??
      workspace_bounds_max_height_m: 2.0 #ecrease to decrease gpu usage

      # do not send ceiling:
      layer_streamer_exclusion_height_m: 1.4      # Blocks above this height will not be streamed.
      layer_streamer_exclusion_radius_m: 7.0

    update_mesh_rate_hz: -1.0 # no mesh while mapping

    decay_tsdf_rate_hz: 0.0
    decay_dynamic_occupancy_rate_hz: 0.0
    clear_map_outside_radius_rate_hz: 0.0
    
    # For better handling of dynamics at increased computational cost, uncomment the following line:
    #mapping_type: "dynamic"
