/**:
  ros__parameters:
    # Lidar settings
    use_lidar: false
    # QoS settings
    input_qos: "SENSOR_DATA"
    # Map clearing settings
    map_clearing_frame_id: "base_link"
    # Rviz visualization
    esdf_slice_bounds_visualization_attachment_frame_id: "base_link"

    static_mapper:
      esdf_slice_height: 0.01
      # Expected to be tuned by user: Slice height depends on zedx mounting.
      esdf_slice_min_height: 0.16
      esdf_slice_max_height: 0.2

    dynamic_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: -0.1
      esdf_slice_max_height: 0.3

    # Original settings
    #   static_mapper:
    #   esdf_slice_height: 0.0
    #   esdf_slice_min_height: -0.1
    #   esdf_slice_max_height: 0.3

    # dynamic_mapper:
    #   esdf_slice_height: 0.0
    #   esdf_slice_min_height: -0.1
    #   esdf_slice_max_height: 0.3